### ISSUE TITLE
Colorscheme does not work with named values on Terminal.app

### ISSUE THREAD

**Issue by craigmac** [teoljungberg/vim-whitescale#7]
I cannot use this colorscheme as it is with named colour values like "white," see `:help cterm-colors`. On Terminal.app and maybe(?) others you'll need to specify instead exact values like ctermbg=234, or else you end up with this:

<img width="1068" alt="Screen Shot 2022-03-14 at 10 11 13 AM" src="https://user-images.githubusercontent.com/7416158/158191130-ae441e75-a1f0-486a-a091-a6c4496ec080.png">

**Comment by craigmac** [comment]
Aha, that's probably it, I found [this workaround](https://stackoverflow.com/questions/1326998/enabling-italics-in-vim-syntax-highlighting-for-mac-terminal) because Terminal.app does not expose enabling italics via any gui menu for some reason. I had to create a new terminfo file that says that it *is* capable of doing it, then it works fine!

**Comment by teoljungberg** [comment]
Glad to hear it worked out!
